<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_address_2</name>
   <tag></tag>
   <elementGuidId>c3764e14-d396-48f9-8d34-5c53416bcc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_address_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_address_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aec9658-eb3d-4b70-be1d-b70fdd9a8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb0ff379-548a-4fb0-848a-9908b8a5f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>ce92f42f-1d90-45b6-b147-b080ee009e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>3deca99a-e7ee-4d5f-86fa-7f2e360eaf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>a6cfbff4-2485-40d7-9ebd-2944011f97c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit etc. (optional)</value>
      <webElementGuid>cae1f921-4967-4395-8ee4-66d68fe2fed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line2</value>
      <webElementGuid>56a9cdd1-7363-4e6c-9add-6e5fed6ae75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit etc. (optional)</value>
      <webElementGuid>bdcaff38-67cc-4bdf-9773-6365d30db305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_address_2&quot;)</value>
      <webElementGuid>f992b75b-8f6e-46ca-b11f-892d78514fec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_address_2']</value>
      <webElementGuid>fa4fe023-6efc-45f7-b255-ed2a3749847c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_address_2_field']/span/input</value>
      <webElementGuid>860c46db-9dac-4e43-bbdb-49389a75ef18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/span/input</value>
      <webElementGuid>ae260f48-69ed-4bef-8f66-68097d7b55cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_address_2' and @id = 'billing_address_2' and @placeholder = 'Apartment, suite, unit etc. (optional)']</value>
      <webElementGuid>b741caf9-27de-49db-abab-1d00f1093894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
